name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dingo-d/phpstan-wp-action@v1
      with:
        level: 5
        paths_file: mail-on-update.php
